"""Materialize formal DPO pairs from audited legal/on-policy negatives.

Synthetic label flips remain an ablation generated by the assemblers.  The
formal main set accepts only a negative tied to a legal S4 candidate and an
existing point-grounded SFT sample.  A legal-candidate negative can be a
reviewed counterfactual completion; it must not be reported as an observed
policy error.  This module does not rank candidates or generate rejected prose;
it validates externally authored/model-produced completions and preserves their
provenance.
"""
from __future__ import annotations

import json
import hashlib
import os
import tempfile
from dataclasses import asdict, dataclass, fields
from pathlib import Path
from typing import Any, Mapping

from .. import config, prompts
from ..envs.obs_utils import bid_is_visible
from ..train.validators import answer_text, parse_action
from .candidates import (FORMAL_CANDIDATE_BODY_NAME, Candidate,
                         CandidateValidationError,
                         assert_candidate_manifest_integrity,
                         validate_candidate_snapshot_artifact)

PREFERENCE_NEGATIVE_SCHEMA_VERSION = "iris.preference_negative.v2"
LEGACY_PREFERENCE_NEGATIVE_SCHEMA_VERSION = "iris.preference_negative.v1"
DEPLOYMENT_NEGATIVE_SOURCES = ("legal_candidate", "on_policy")


class PreferenceMaterializationError(ValueError):
    pass


@dataclass(frozen=True)
class PreferenceNegative:
    schema_version: str
    error_id: str
    sample_id: str
    negative_source: str
    candidate_id: str
    rejected_completion: str
    preference_source: str
    policy_model_version: str
    reviewer: str
    timestamp: str
    evidence: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def validate(self) -> None:
        errors: list[str] = []
        if self.schema_version not in {
                PREFERENCE_NEGATIVE_SCHEMA_VERSION,
                LEGACY_PREFERENCE_NEGATIVE_SCHEMA_VERSION}:
            errors.append("bad schema_version")
        for name in ("error_id", "sample_id", "negative_source",
                     "rejected_completion", "preference_source", "reviewer",
                     "timestamp"):
            if not str(getattr(self, name) or "").strip():
                errors.append(f"missing {name}")
        if self.negative_source not in DEPLOYMENT_NEGATIVE_SOURCES:
            errors.append("negative_source must be legal_candidate or on_policy")
        if self.negative_source == "legal_candidate" and not self.candidate_id:
            errors.append("legal_candidate negative requires candidate_id")
        if self.negative_source == "on_policy":
            if self.schema_version != PREFERENCE_NEGATIVE_SCHEMA_VERSION:
                errors.append(
                    "legacy v1 cannot establish trace-backed on_policy provenance")
            if not self.policy_model_version:
                errors.append("on_policy negative requires policy_model_version")
            required_evidence = {
                "trace_id", "input_messages_sha256", "raw_completion_sha256",
                "error_types", "action_legal", "action_kind",
                "completion_construction", "observed_policy_error",
            }
            missing = sorted(required_evidence - set(self.evidence or {}))
            if missing:
                errors.append(
                    "on_policy negative lacks trace evidence: " + ",".join(missing))
            elif self.evidence.get("completion_construction") != \
                    "raw_model_output":
                errors.append(
                    "on_policy completion_construction must be raw_model_output")
            elif self.evidence.get("observed_policy_error") is not True:
                errors.append("on_policy observed_policy_error must be true")
            if not isinstance((self.evidence or {}).get("error_types"), list) or \
                    not (self.evidence or {}).get("error_types"):
                errors.append("on_policy error_types must be a non-empty list")
            if not isinstance((self.evidence or {}).get("action_legal"), bool):
                errors.append("on_policy action_legal must be boolean")
            if (self.evidence or {}).get("action_legal") is False and \
                    self.candidate_id:
                errors.append("illegal on_policy action cannot claim candidate_id")
        if "__" in self.error_id:
            errors.append("error_id must not contain '__'")
        if not isinstance(self.evidence, dict) or not self.evidence:
            errors.append("non-empty preference evidence is required")
        if (self.negative_source != "on_policy" and
                parse_action(answer_text(self.rejected_completion)) is None):
            errors.append("rejected_completion must contain one parseable <answer> action")
        if errors:
            raise PreferenceMaterializationError(
                f"{self.error_id or '<missing error_id>'}: " + "; ".join(errors))

    @classmethod
    def from_dict(cls, row: Mapping[str, Any]) -> "PreferenceNegative":
        unknown = sorted(set(row) - {f.name for f in fields(cls)})
        if unknown:
            raise PreferenceMaterializationError(
                f"unknown preference-negative fields: {unknown}")
        try:
            record = cls(**dict(row))
        except TypeError as exc:
            raise PreferenceMaterializationError(str(exc)) from exc
        record.validate()
        return record


def _jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.open(encoding="utf-8")
            if line.strip()]


def load_preference_negatives(path: Path) -> dict[str, PreferenceNegative]:
    records: dict[str, PreferenceNegative] = {}
    for line_no, row in enumerate(_jsonl(path), 1):
        try:
            record = PreferenceNegative.from_dict(row)
        except PreferenceMaterializationError as exc:
            raise PreferenceMaterializationError(f"{path}:{line_no}: {exc}") from exc
        if record.error_id in records:
            raise PreferenceMaterializationError(
                f"{path}:{line_no}: duplicate error_id {record.error_id}")
        records[record.error_id] = record
    return records


def _candidate_index(path: Path) -> dict[str, Candidate]:
    result: dict[str, Candidate] = {}
    for line_no, row in enumerate(_jsonl(path), 1):
        try:
            candidate = Candidate.from_dict(row)
        except CandidateValidationError as exc:
            raise PreferenceMaterializationError(f"{path}:{line_no}: {exc}") from exc
        if candidate.candidate_id in result:
            raise PreferenceMaterializationError(
                f"{path}:{line_no}: duplicate candidate_id")
        result[candidate.candidate_id] = candidate
    return result


def build_formal_dpo_pairs(
        sft_rows: list[dict], candidates: Mapping[str, Candidate],
        negatives: Mapping[str, PreferenceNegative], *,
        on_policy_traces: Mapping[str, Any] | None = None) -> list[dict]:
    """Exact sample→snapshot candidate→audited negative join."""
    by_sample = {str(row.get("sample_id") or ""): row for row in sft_rows}
    if len(by_sample) != len(sft_rows) or "" in by_sample:
        raise PreferenceMaterializationError("SFT sample_id values must be unique")
    pairs: list[dict] = []
    for error_id in sorted(negatives):
        negative = negatives[error_id]
        source = by_sample.get(negative.sample_id)
        if source is None:
            raise PreferenceMaterializationError(
                f"{error_id}: unknown source sample_id {negative.sample_id}")
        meta = dict(source.get("meta") or {})
        if meta.get("formal_dataset") is not True:
            raise PreferenceMaterializationError(
                f"{error_id}: source sample is not formal")
        messages = list(source.get("messages") or [])
        if len(messages) != 3 or [m.get("role") for m in messages] != [
                "system", "user", "assistant"]:
            raise PreferenceMaterializationError(
                f"{error_id}: source must have stateless system/user/assistant topology")
        trace = None
        if negative.negative_source == "on_policy":
            trace_id = str((negative.evidence or {}).get("trace_id") or "")
            trace = (on_policy_traces or {}).get(trace_id)
            if trace is None:
                raise PreferenceMaterializationError(
                    f"{error_id}: on_policy trace {trace_id or '<missing>'} "
                    "was not loaded through the verified trace manifest")
            trace_expected = {
                "source_sample_id": negative.sample_id,
                "input_messages_sha256": (negative.evidence or {}).get(
                    "input_messages_sha256"),
                "raw_completion_sha256": (negative.evidence or {}).get(
                    "raw_completion_sha256"),
                "raw_completion": negative.rejected_completion,
                "candidate_id": negative.candidate_id or None,
            }
            trace_mismatch = [
                name for name, value in trace_expected.items()
                if getattr(trace, name) != value]
            if trace_mismatch:
                raise PreferenceMaterializationError(
                    f"{error_id}: preference/verified-trace mismatch " +
                    ",".join(trace_mismatch))
            if trace.input_messages != messages[:-1]:
                raise PreferenceMaterializationError(
                    f"{error_id}: DPO prompt is not byte-exact model input")
            if list(trace.error_types) != list(
                    (negative.evidence or {}).get("error_types") or []):
                raise PreferenceMaterializationError(
                    f"{error_id}: error_types disagree with verified trace")
            if trace.eligible_as_negative is not True:
                raise PreferenceMaterializationError(
                    f"{error_id}: correct rollout output cannot be a negative")

        candidate = (candidates.get(negative.candidate_id)
                     if negative.candidate_id else None)
        if negative.candidate_id and candidate is None:
            raise PreferenceMaterializationError(
                f"{error_id}: unknown candidate_id {negative.candidate_id}")
        if candidate is not None and candidate.state_id != str(
                meta.get("state_id") or ""):
            raise PreferenceMaterializationError(
                f"{error_id}: candidate/source state_id mismatch")
        if negative.negative_source == "legal_candidate" and candidate is None:
            raise PreferenceMaterializationError(
                f"{error_id}: legal_candidate requires a formal candidate")
        if trace is not None and trace.action_kind == "legal" and \
                trace.parsed_action and trace.parsed_action.get("bid") and \
                candidate is None:
            raise PreferenceMaterializationError(
                f"{error_id}: legal DOM on_policy action lacks matched candidate")
        observation = prompts.parse_observation_message(messages[1].get("content", ""))
        # Full legality is replayed once against the immutable, unpruned state
        # bank in ``materialize_formal_dpo``.  The policy input is intentionally
        # compacted, so hashing it as though it were the source snapshot would
        # reject every legitimately pruned sample.  Here we enforce the two
        # properties that must survive compaction: the pinned snapshot identity
        # and visibility of the exact interactive control.
        source_snapshot_hash = str(meta.get("candidate_snapshot_hash") or "")
        if candidate is not None:
            candidate.validate_record()
            if candidate.snapshot_hash != source_snapshot_hash:
                raise PreferenceMaterializationError(
                    f"{error_id}: candidate/source snapshot_hash mismatch")
            if not bid_is_visible(observation, candidate.bid):
                raise PreferenceMaterializationError(
                    f"{error_id}: candidate bid [{candidate.bid}] is absent from "
                    "the compacted policy observation")
            rejected_action = parse_action(answer_text(negative.rejected_completion))
            candidate_primitive = candidate.canonical_action.split(":", 1)[0]
            if (rejected_action is None or rejected_action.bid != candidate.bid or
                    rejected_action.name != candidate_primitive):
                raise PreferenceMaterializationError(
                    f"{error_id}: rejected action does not execute candidate "
                    f"primitive/bid {candidate_primitive}([{candidate.bid}])")
        chosen = str(messages[2].get("content") or "")
        if chosen == negative.rejected_completion:
            raise PreferenceMaterializationError(
                f"{error_id}: rejected completion equals chosen completion")
        pair_meta = dict(meta)
        pair_type = (
            "observed_policy_error"
            if negative.negative_source == "on_policy"
            else "reviewed_legal_counterfactual"
        )
        pair_meta.update({
            "pair_type": pair_type,
            "source_sample_id": negative.sample_id,
            "negative_source": negative.negative_source,
            # ``candidate_id`` remains the executed source candidate pinned by
            # the point-level grounding row.  ``negative_candidate_id`` names
            # the legal action support of the rejected completion; it does not
            # imply a different action.  The current reviewed counterfactuals
            # intentionally reuse the expert action while changing the unsafe
            # decision/completion, and must not be reported as on-policy errors
            # or as alternative-candidate diversity.
            "negative_candidate_id": candidate.candidate_id if candidate else "",
            "negative_candidate_category": candidate.category if candidate else "",
            "negative_candidate_snapshot_hash": (
                candidate.snapshot_hash if candidate else ""),
            "legal_at_snapshot": (
                bool(trace.action_legal) if trace is not None else True),
            "policy_model_version": negative.policy_model_version,
            "preference_source": negative.preference_source,
            "preference_error_id": negative.error_id,
            "preference_reviewer": negative.reviewer,
            "preference_timestamp": negative.timestamp,
            "preference_evidence": negative.evidence,
            "dataset_tier": "formal_point",
        })
        if trace is not None:
            pair_meta.update({
                "on_policy_trace_verified": True,
                "on_policy_trace_id": trace.trace_id,
                "on_policy_input_messages_sha256": trace.input_messages_sha256,
                "on_policy_raw_completion_sha256": trace.raw_completion_sha256,
                "on_policy_error_types": list(trace.error_types),
                "on_policy_action_kind": trace.action_kind,
                "on_policy_action_legal": trace.action_legal,
                "on_policy_rollout_run_id": trace.rollout_run_id,
            })
        pairs.append({
            "pair_id": f"{negative.sample_id}__{negative.error_id}",
            "prompt": messages[:-1], "chosen": chosen,
            "rejected": negative.rejected_completion, "meta": pair_meta,
        })
    if not pairs:
        raise PreferenceMaterializationError("preference import contains zero rows")
    return pairs


def build_reviewed_legal_counterfactual_negatives(
        sft_rows: list[dict], candidates: Mapping[str, Candidate],
        synthetic_ablation_rows: list[dict], *, reviewer: str,
        timestamp: str) -> list[PreferenceNegative]:
    """Promote only the *action support* of a legal S4 counterfactual.

    The rejected prose is reused from the explicitly synthetic
    ``goal_violation`` ablation, and that construction is recorded verbatim in
    ``evidence``.  Consequently these rows satisfy the deployment-shaped legal
    candidate gate, but remain distinguishable from on-policy model errors.
    Every formal constraint sample must close the same point/state/snapshot
    join; the function fails rather than silently dropping an awkward row.
    """
    if not str(reviewer or "").strip() or not str(timestamp or "").strip():
        raise PreferenceMaterializationError("reviewer and timestamp are required")
    ablation_by_sample: dict[str, list[dict]] = {}
    for pair in synthetic_ablation_rows:
        meta = pair.get("meta") or {}
        if (meta.get("pair_type") == "goal_violation" and
                meta.get("negative_source") == "synthetic_flip"):
            pair_id = str(pair.get("pair_id") or "")
            source_id = str(meta.get("source_sample_id") or "")
            if not source_id and pair_id.endswith("__goal_violation"):
                source_id = pair_id.removesuffix("__goal_violation")
            if not source_id or pair_id != f"{source_id}__goal_violation":
                raise PreferenceMaterializationError(
                    f"malformed synthetic goal_violation identity {pair_id!r}")
            ablation_by_sample.setdefault(source_id, []).append(pair)

    records: list[PreferenceNegative] = []
    constraint_rows = [
        row for row in sft_rows
        if (row.get("meta") or {}).get("variant") == "constraint"
    ]
    if not constraint_rows:
        raise PreferenceMaterializationError(
            "formal SFT contains zero constraint samples")
    for source in sorted(constraint_rows, key=lambda row: str(row.get("sample_id"))):
        sample_id = str(source.get("sample_id") or "")
        meta = source.get("meta") or {}
        required_truth = {
            "formal_dataset": True,
            "is_mock": False,
            "collector_success": True,
            "decision": "AVOID",
            "violates_constraint": True,
            "policy_constraint_truth": True,
            "action_legal": True,
            "legal_at_snapshot": True,
        }
        mismatched = [key for key, value in required_truth.items()
                      if meta.get(key) != value]
        if not sample_id or mismatched:
            raise PreferenceMaterializationError(
                f"{sample_id or '<missing sample_id>'}: constraint truth gate "
                f"failed for {mismatched}")
        candidate_id = str(meta.get("candidate_id") or "")
        candidate = candidates.get(candidate_id)
        if candidate is None:
            raise PreferenceMaterializationError(
                f"{sample_id}: missing formal expert candidate {candidate_id}")
        expected = {
            "state_id": str(meta.get("state_id") or ""),
            "snapshot_hash": str(meta.get("candidate_snapshot_hash") or ""),
            "legal_at_snapshot": True,
        }
        candidate_mismatch = [key for key, value in expected.items()
                              if getattr(candidate, key) != value]
        if candidate_mismatch:
            raise PreferenceMaterializationError(
                f"{sample_id}: expert candidate mismatch {candidate_mismatch}")
        matches = ablation_by_sample.get(sample_id, [])
        if len(matches) != 1:
            raise PreferenceMaterializationError(
                f"{sample_id}: expected one synthetic goal_violation row, "
                f"found {len(matches)}")
        source_pair = matches[0]
        rejected = str(source_pair.get("rejected") or "")
        rejected_action = parse_action(answer_text(rejected))
        primitive = candidate.canonical_action.split(":", 1)[0]
        if (rejected_action is None or rejected_action.name != primitive or
                rejected_action.bid != candidate.bid):
            raise PreferenceMaterializationError(
                f"{sample_id}: counterfactual does not execute formal candidate")
        digest = hashlib.sha256(
            f"{sample_id}\0{candidate_id}\0{rejected}".encode("utf-8")
        ).hexdigest()[:20]
        record = PreferenceNegative(
            schema_version=PREFERENCE_NEGATIVE_SCHEMA_VERSION,
            error_id=f"legal-counterfactual-{digest}",
            sample_id=sample_id,
            negative_source="legal_candidate",
            candidate_id=candidate_id,
            rejected_completion=rejected,
            preference_source=(
                "explicit_policy_truth+legal_candidate_counterfactual"),
            policy_model_version="",
            reviewer=str(reviewer),
            timestamp=str(timestamp),
            evidence={
                "reviewer_type": "model_assisted_engineering",
                "observed_policy_error": False,
                "completion_construction": "counterfactual_template",
                "source_ablation_pair_id": source_pair.get("pair_id"),
                "source_ablation_rejected_sha256": hashlib.sha256(
                    rejected.encode("utf-8")).hexdigest(),
                "candidate_snapshot_hash": candidate.snapshot_hash,
                "evaluation_case_id": meta.get("evaluation_case_id"),
                "normative_policy_id": meta.get("normative_policy_id"),
                "normative_policy_version": meta.get("normative_policy_version"),
                "truth_basis": "violates_constraint=true",
            },
        )
        record.validate()
        records.append(record)
    return records


def build_trace_backed_on_policy_negatives(
        sft_rows: list[dict], traces: Mapping[str, Any], *,
        reviewer: str, timestamp: str) -> list[PreferenceNegative]:
    """Convert only manifest-verified model errors into preference records."""
    if not str(reviewer or "").strip() or not str(timestamp or "").strip():
        raise PreferenceMaterializationError("reviewer and timestamp are required")
    by_sample = {str(row.get("sample_id") or ""): row for row in sft_rows}
    if "" in by_sample or len(by_sample) != len(sft_rows):
        raise PreferenceMaterializationError(
            "formal SFT sample_id values must be unique")
    records: list[PreferenceNegative] = []
    for trace_id in sorted(traces):
        trace = traces[trace_id]
        source = by_sample.get(trace.source_sample_id)
        if source is None:
            raise PreferenceMaterializationError(
                f"{trace_id}: unknown source sample {trace.source_sample_id}")
        messages = source.get("messages") or []
        if len(messages) != 3 or trace.input_messages != messages[:-1]:
            raise PreferenceMaterializationError(
                f"{trace_id}: model input is not byte-exact source SFT prompt")
        if not trace.eligible_as_negative or not trace.error_types:
            raise PreferenceMaterializationError(
                f"{trace_id}: correct output cannot be authored as a negative")
        provider = str(trace.policy_provenance.get("provider") or "unknown")
        requested = str(trace.policy_provenance.get("model") or "unknown")
        model_version = f"{provider}:{requested}->{trace.model_returned}"
        digest = hashlib.sha256(
            f"{trace.source_sample_id}\0{trace.trace_id}".encode("utf-8")
        ).hexdigest()[:20]
        record = PreferenceNegative(
            schema_version=PREFERENCE_NEGATIVE_SCHEMA_VERSION,
            error_id=f"on-policy-{digest}",
            sample_id=trace.source_sample_id,
            negative_source="on_policy",
            candidate_id=trace.candidate_id or "",
            rejected_completion=trace.raw_completion,
            preference_source="verified_rollout_trace+explicit_policy_truth",
            policy_model_version=model_version,
            reviewer=str(reviewer), timestamp=str(timestamp),
            evidence={
                "trace_id": trace.trace_id,
                "rollout_run_id": trace.rollout_run_id,
                "evaluation_case_id": trace.evaluation_case_id,
                "probe_point_id": trace.probe_point_id,
                "input_messages_sha256": trace.input_messages_sha256,
                "raw_completion_sha256": trace.raw_completion_sha256,
                "policy_provenance_sha256": trace.policy_provenance_sha256,
                "error_types": list(trace.error_types),
                "action_legal": trace.action_legal,
                "action_kind": trace.action_kind,
                "completion_construction": "raw_model_output",
                "observed_policy_error": True,
                "candidate_id": trace.candidate_id,
                "truth_source": trace.truth_source,
            },
        )
        record.validate()
        records.append(record)
    if not records:
        raise PreferenceMaterializationError(
            "verified trace artifact contains zero eligible model errors")
    return records


def _atomic_new_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise PreferenceMaterializationError(
            f"refusing to overwrite existing formal DPO artifact {path}")
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            for row in rows:
                handle.write(json.dumps(row, ensure_ascii=False,
                                        sort_keys=True) + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def author_legal_counterfactual_negatives(
        data_root: Path, output_path: Path, *, family: str,
        reviewer: str, timestamp: str) -> dict:
    """Create an immutable, auditable authoring artifact for formal DPO."""
    root = Path(data_root)
    if family not in {"single", "multiturn"}:
        raise PreferenceMaterializationError("family must be single or multiturn")
    formal = root / "train" / "formal"
    ablation = root / "train" / "ablation"
    sft_path = formal / (
        config.FORMAL_SFT_PATH.name if family == "single"
        else config.FORMAL_MULTITURN_SFT_PATH.name)
    ablation_path = ablation / (
        "iris_dpo_synthetic_point_v1.jsonl" if family == "single"
        else "iris_dpo_multiturn_synthetic_v1.jsonl")
    try:
        candidates = assert_candidate_manifest_integrity(
            root / "raw" / "candidates" / FORMAL_CANDIDATE_BODY_NAME)
        validate_candidate_snapshot_artifact(
            candidates, root / "raw" / "state_bank")
    except CandidateValidationError as exc:
        raise PreferenceMaterializationError(
            f"formal candidate artifact invalid: {exc}") from exc
    records = build_reviewed_legal_counterfactual_negatives(
        _jsonl(sft_path), candidates, _jsonl(ablation_path),
        reviewer=reviewer, timestamp=timestamp)
    _atomic_new_jsonl(Path(output_path), [record.to_dict() for record in records])
    return {
        "family": family,
        "n_records": len(records),
        "output": str(output_path),
        "negative_source_dist": {"legal_candidate": len(records)},
        "observed_policy_errors": 0,
        "completion_construction": "counterfactual_template",
    }


def author_on_policy_negatives(
        data_root: Path, trace_body: Path, output_path: Path, *,
        family: str, reviewer: str, timestamp: str,
        trace_manifest: Path | None = None) -> dict:
    """Freeze raw model errors after exact trace/body/truth verification."""
    from ..data.governance import formal_release_context
    from ..eval.on_policy import (OnPolicyTraceError,
                                  load_verified_negative_traces)
    from ..eval.truth import load_truth_records

    root = Path(data_root)
    if family not in {"single", "multiturn"}:
        raise PreferenceMaterializationError("family must be single or multiturn")
    sft_path = root / "train" / "formal" / (
        config.FORMAL_SFT_PATH.name if family == "single"
        else config.FORMAL_MULTITURN_SFT_PATH.name)
    context = formal_release_context(root)
    if context.grounding_error or context.truth_error:
        raise PreferenceMaterializationError(
            "formal point/truth context is invalid: " +
            (context.grounding_error or context.truth_error))
    try:
        truths = load_truth_records(
            root / "eval" / "truth.jsonl", points=context.points)
        traces = load_verified_negative_traces(
            Path(trace_body), Path(trace_manifest) if trace_manifest else None,
            truths=truths)
    except (OnPolicyTraceError, OSError, ValueError) as exc:
        raise PreferenceMaterializationError(
            f"on-policy trace verification failed: {exc}") from exc
    records = build_trace_backed_on_policy_negatives(
        _jsonl(sft_path), traces, reviewer=reviewer, timestamp=timestamp)
    _atomic_new_jsonl(Path(output_path), [record.to_dict() for record in records])
    return {
        "family": family,
        "n_records": len(records),
        "output": str(output_path),
        "negative_source_dist": {"on_policy": len(records)},
        "trace_body": str(trace_body),
        "trace_manifest": str(trace_manifest or "<derived>"),
    }


def materialize_formal_dpo(data_root: Path, negatives_path: Path, *,
                           family: str = "single",
                           trace_body: Path | None = None,
                           trace_manifest: Path | None = None,
                           output_path: Path | None = None) -> dict:
    """Production entry point with trainer and exact point/truth provenance gates."""
    from ..train.dpo import validate_rows
    from ..train.validators import formal_point_join_problems

    root = Path(data_root)
    if family not in {"single", "multiturn"}:
        raise PreferenceMaterializationError("family must be single or multiturn")
    base = root / "train" / "formal"
    sft_name = (config.FORMAL_SFT_PATH.name if family == "single" else
                config.FORMAL_MULTITURN_SFT_PATH.name)
    out_name = (config.FORMAL_DPO_PATH.name if family == "single" else
                config.FORMAL_MULTITURN_DPO_PATH.name)
    sft_rows = _jsonl(base / sft_name)
    if not sft_rows:
        raise PreferenceMaterializationError(
            f"formal source SFT is empty: {base / sft_name}")
    try:
        candidates = assert_candidate_manifest_integrity(
            root / "raw" / "candidates" / FORMAL_CANDIDATE_BODY_NAME)
        validate_candidate_snapshot_artifact(
            candidates, root / "raw" / "state_bank")
    except CandidateValidationError as exc:
        raise PreferenceMaterializationError(
            f"candidate artifact invalid: {exc}") from exc
    negatives = load_preference_negatives(Path(negatives_path))
    on_policy_traces: Mapping[str, Any] | None = None
    if any(record.negative_source == "on_policy"
           for record in negatives.values()):
        if trace_body is None:
            raise PreferenceMaterializationError(
                "on_policy negatives require --trace-body and verified manifest")
        from ..data.governance import formal_release_context
        from ..eval.on_policy import (OnPolicyTraceError,
                                      load_verified_negative_traces)
        from ..eval.truth import load_truth_records

        context = formal_release_context(root)
        if context.grounding_error or context.truth_error:
            raise PreferenceMaterializationError(
                "formal point/truth context is invalid")
        try:
            truths = load_truth_records(
                root / "eval" / "truth.jsonl", points=context.points)
            on_policy_traces = load_verified_negative_traces(
                Path(trace_body),
                Path(trace_manifest) if trace_manifest else None,
                truths=truths)
        except (OnPolicyTraceError, OSError, ValueError) as exc:
            raise PreferenceMaterializationError(
                f"on-policy trace verification failed: {exc}") from exc
    pairs = build_formal_dpo_pairs(
        sft_rows, candidates, negatives,
        on_policy_traces=on_policy_traces)
    report = validate_rows(pairs, formal=True)
    problems = list(report["problems"])
    problems.extend(formal_point_join_problems(pairs, root))
    if problems:
        raise PreferenceMaterializationError(
            "formal DPO gates failed: " + " | ".join(problems[:10]))
    out_path = Path(output_path) if output_path else base / out_name
    _atomic_new_jsonl(out_path, pairs)
    return {
        "family": family, "n_pairs": len(pairs), "path": str(out_path),
        "negative_source_dist": report["negative_source_dist"],
        "deployment_negative_ratio": report["deployment_negative_ratio"],
    }
