"""Materialize formal DPO pairs from audited legal/on-policy errors.

Synthetic label flips remain an ablation generated by the assemblers.  The
formal main set accepts only a recorded error tied to a legal S4 candidate and
an existing point-grounded SFT sample.  This module does not rank candidates or
generate rejected prose; it validates externally reviewed/model-produced
completions and preserves their provenance.
"""
from __future__ import annotations

import json
import os
import tempfile
from dataclasses import asdict, dataclass, fields
from pathlib import Path
from typing import Any, Mapping

from .. import prompts
from ..envs.obs_utils import bid_is_visible
from ..train.validators import answer_text, parse_action
from .candidates import (Candidate, CandidateValidationError,
                         assert_candidate_manifest_integrity,
                         validate_candidate_snapshot_artifact)

PREFERENCE_NEGATIVE_SCHEMA_VERSION = "iris.preference_negative.v1"
DEPLOYMENT_NEGATIVE_SOURCES = ("legal_candidate", "on_policy")


class PreferenceMaterializationError(ValueError):
    pass


@dataclass(frozen=True)
class PreferenceNegative:
    schema_version: str
    error_id: str
    sample_id: str
    negative_source: str
    candidate_id: str
    rejected_completion: str
    preference_source: str
    policy_model_version: str
    reviewer: str
    timestamp: str
    evidence: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def validate(self) -> None:
        errors: list[str] = []
        if self.schema_version != PREFERENCE_NEGATIVE_SCHEMA_VERSION:
            errors.append("bad schema_version")
        for name in ("error_id", "sample_id", "negative_source", "candidate_id",
                     "rejected_completion", "preference_source", "reviewer",
                     "timestamp"):
            if not str(getattr(self, name) or "").strip():
                errors.append(f"missing {name}")
        if self.negative_source not in DEPLOYMENT_NEGATIVE_SOURCES:
            errors.append("negative_source must be legal_candidate or on_policy")
        if self.negative_source == "on_policy" and not self.policy_model_version:
            errors.append("on_policy negative requires policy_model_version")
        if "__" in self.error_id:
            errors.append("error_id must not contain '__'")
        if not isinstance(self.evidence, dict) or not self.evidence:
            errors.append("non-empty preference evidence is required")
        if parse_action(answer_text(self.rejected_completion)) is None:
            errors.append("rejected_completion must contain one parseable <answer> action")
        if errors:
            raise PreferenceMaterializationError(
                f"{self.error_id or '<missing error_id>'}: " + "; ".join(errors))

    @classmethod
    def from_dict(cls, row: Mapping[str, Any]) -> "PreferenceNegative":
        unknown = sorted(set(row) - {f.name for f in fields(cls)})
        if unknown:
            raise PreferenceMaterializationError(
                f"unknown preference-negative fields: {unknown}")
        try:
            record = cls(**dict(row))
        except TypeError as exc:
            raise PreferenceMaterializationError(str(exc)) from exc
        record.validate()
        return record


def _jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.open(encoding="utf-8")
            if line.strip()]


def load_preference_negatives(path: Path) -> dict[str, PreferenceNegative]:
    records: dict[str, PreferenceNegative] = {}
    for line_no, row in enumerate(_jsonl(path), 1):
        try:
            record = PreferenceNegative.from_dict(row)
        except PreferenceMaterializationError as exc:
            raise PreferenceMaterializationError(f"{path}:{line_no}: {exc}") from exc
        if record.error_id in records:
            raise PreferenceMaterializationError(
                f"{path}:{line_no}: duplicate error_id {record.error_id}")
        records[record.error_id] = record
    return records


def _candidate_index(path: Path) -> dict[str, Candidate]:
    result: dict[str, Candidate] = {}
    for line_no, row in enumerate(_jsonl(path), 1):
        try:
            candidate = Candidate.from_dict(row)
        except CandidateValidationError as exc:
            raise PreferenceMaterializationError(f"{path}:{line_no}: {exc}") from exc
        if candidate.candidate_id in result:
            raise PreferenceMaterializationError(
                f"{path}:{line_no}: duplicate candidate_id")
        result[candidate.candidate_id] = candidate
    return result


def build_formal_dpo_pairs(sft_rows: list[dict], candidates: Mapping[str, Candidate],
                           negatives: Mapping[str, PreferenceNegative]) -> list[dict]:
    """Exact sample→snapshot candidate→observed error join."""
    by_sample = {str(row.get("sample_id") or ""): row for row in sft_rows}
    if len(by_sample) != len(sft_rows) or "" in by_sample:
        raise PreferenceMaterializationError("SFT sample_id values must be unique")
    pairs: list[dict] = []
    for error_id in sorted(negatives):
        negative = negatives[error_id]
        source = by_sample.get(negative.sample_id)
        if source is None:
            raise PreferenceMaterializationError(
                f"{error_id}: unknown source sample_id {negative.sample_id}")
        meta = dict(source.get("meta") or {})
        if meta.get("formal_dataset") is not True:
            raise PreferenceMaterializationError(
                f"{error_id}: source sample is not formal")
        candidate = candidates.get(negative.candidate_id)
        if candidate is None:
            raise PreferenceMaterializationError(
                f"{error_id}: unknown candidate_id {negative.candidate_id}")
        if candidate.state_id != str(meta.get("state_id") or ""):
            raise PreferenceMaterializationError(
                f"{error_id}: candidate/source state_id mismatch")
        messages = list(source.get("messages") or [])
        if len(messages) != 3 or [m.get("role") for m in messages] != [
                "system", "user", "assistant"]:
            raise PreferenceMaterializationError(
                f"{error_id}: source must have stateless system/user/assistant topology")
        observation = prompts.parse_observation_message(messages[1].get("content", ""))
        # Full legality is replayed once against the immutable, unpruned state
        # bank in ``materialize_formal_dpo``.  The policy input is intentionally
        # compacted, so hashing it as though it were the source snapshot would
        # reject every legitimately pruned sample.  Here we enforce the two
        # properties that must survive compaction: the pinned snapshot identity
        # and visibility of the exact interactive control.
        candidate.validate_record()
        source_snapshot_hash = str(meta.get("candidate_snapshot_hash") or "")
        if candidate.snapshot_hash != source_snapshot_hash:
            raise PreferenceMaterializationError(
                f"{error_id}: candidate/source snapshot_hash mismatch")
        if not bid_is_visible(observation, candidate.bid):
            raise PreferenceMaterializationError(
                f"{error_id}: candidate bid [{candidate.bid}] is absent from "
                "the compacted policy observation")
        rejected_action = parse_action(answer_text(negative.rejected_completion))
        candidate_primitive = candidate.canonical_action.split(":", 1)[0]
        if (rejected_action is None or rejected_action.bid != candidate.bid or
                rejected_action.name != candidate_primitive):
            raise PreferenceMaterializationError(
                f"{error_id}: rejected action does not execute candidate "
                f"primitive/bid {candidate_primitive}([{candidate.bid}])")
        chosen = str(messages[2].get("content") or "")
        if chosen == negative.rejected_completion:
            raise PreferenceMaterializationError(
                f"{error_id}: rejected completion equals chosen completion")
        pair_meta = dict(meta)
        pair_meta.update({
            "pair_type": "observed_policy_error",
            "source_sample_id": negative.sample_id,
            "negative_source": negative.negative_source,
            # ``candidate_id`` remains the executed source candidate pinned by
            # the point-level grounding row.  A preference negative is a
            # different action and therefore needs its own identity field.
            "negative_candidate_id": candidate.candidate_id,
            "negative_candidate_category": candidate.category,
            "negative_candidate_snapshot_hash": candidate.snapshot_hash,
            "legal_at_snapshot": True,
            "policy_model_version": negative.policy_model_version,
            "preference_source": negative.preference_source,
            "preference_error_id": negative.error_id,
            "preference_reviewer": negative.reviewer,
            "preference_timestamp": negative.timestamp,
            "preference_evidence": negative.evidence,
            "dataset_tier": "formal_point",
        })
        pairs.append({
            "pair_id": f"{negative.sample_id}__{negative.error_id}",
            "prompt": messages[:-1], "chosen": chosen,
            "rejected": negative.rejected_completion, "meta": pair_meta,
        })
    if not pairs:
        raise PreferenceMaterializationError("preference import contains zero rows")
    return pairs


def _atomic_new_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise PreferenceMaterializationError(
            f"refusing to overwrite existing formal DPO artifact {path}")
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            for row in rows:
                handle.write(json.dumps(row, ensure_ascii=False,
                                        sort_keys=True) + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def materialize_formal_dpo(data_root: Path, negatives_path: Path, *,
                           family: str = "single") -> dict:
    """Production entry point with trainer and exact point/truth provenance gates."""
    from ..train.dpo import validate_rows
    from ..train.validators import formal_point_join_problems

    root = Path(data_root)
    if family not in {"single", "multiturn"}:
        raise PreferenceMaterializationError("family must be single or multiturn")
    base = root / "train" / "formal"
    sft_name = ("iris_sft_point_v1.jsonl" if family == "single" else
                "iris_sft_multiturn_point_v1.jsonl")
    out_name = ("iris_dpo_point_v1.jsonl" if family == "single" else
                "iris_dpo_multiturn_point_v1.jsonl")
    sft_rows = _jsonl(base / sft_name)
    if not sft_rows:
        raise PreferenceMaterializationError(
            f"formal source SFT is empty: {base / sft_name}")
    try:
        candidates = assert_candidate_manifest_integrity(
            root / "raw" / "candidates" / "iris_candidates.v3.jsonl")
        validate_candidate_snapshot_artifact(
            candidates, root / "raw" / "state_bank")
    except CandidateValidationError as exc:
        raise PreferenceMaterializationError(
            f"candidate artifact invalid: {exc}") from exc
    negatives = load_preference_negatives(Path(negatives_path))
    pairs = build_formal_dpo_pairs(sft_rows, candidates, negatives)
    report = validate_rows(pairs, formal=True)
    problems = list(report["problems"])
    problems.extend(formal_point_join_problems(pairs, root))
    if problems:
        raise PreferenceMaterializationError(
            "formal DPO gates failed: " + " | ".join(problems[:10]))
    out_path = base / out_name
    _atomic_new_jsonl(out_path, pairs)
    return {
        "family": family, "n_pairs": len(pairs), "path": str(out_path),
        "negative_source_dist": report["negative_source_dist"],
        "deployment_negative_ratio": report["deployment_negative_ratio"],
    }
